#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This sets up a parallel checkout and links your personal, git-excluded\n' "$DIM"
  printf '  layer back to the canonical one. Nothing is overwritten; stop any time\n'
  printf '  with Ctrl-C and re-run.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — a new git worktree for parallel work, with the personal
# git-excluded layer symlinked back to the canonical checkout.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Personal layer: paths listed in .git/info/exclude that live at the repo root.
PERSONAL_ROOT=(CLAUDE.md CONTEXT.md CODING_STANDARDS.md CONTRIBUTING.md docs .scratch openspec)
# .claude stays a REAL directory (settings.json is tracked; worktrees/, locks
# and checkpoints must stay per-worktree). Only these children are linked.
PERSONAL_CLAUDE=(settings.local.json commands rules docs skills)

usage() {
  cat <<HELP
$(basename "$0") — create a git worktree for parallel work on this repo.

USAGE
  $(basename "$0") [-h|--help]

  Interactive: it prompts for the worktree name, branch and base branch.
  There are no other flags.

WHAT IT DOES
  Creates <parent>/worktrees/<repo>/<name> next to the canonical checkout,
  branching off origin/<base> (or checking out <branch> if it already exists).

  Your personal layer is git-excluded via .git/info/exclude, so git never
  carries it into a worktree. This script restores it:

    symlinked   ${PERSONAL_ROOT[*]}
                $(printf '.claude/%s ' "${PERSONAL_CLAUDE[@]}")
    copied      every untracked .env* (so each workspace runs its own port)
    real dir    .claude/ — settings.json is tracked and session state
                (worktrees/, locks, checkpoints) must stay per-worktree

  Symlinks, never copies: one edit to CLAUDE.md or an ADR reaches every
  workspace. .env* is copied precisely so it does not.

  The last stage checks that the new worktree's git status is clean. If a
  personal path shows up there, .git/info/exclude is missing a pattern —
  note that a symlink does not match a trailing-slash pattern, so 'docs'
  is needed alongside 'docs/'.

REMOVING A WORKTREE
  git -C <main-checkout> worktree remove <path>
HELP
}

case "${1:-}" in
  -h|--help) usage; exit 0 ;;
  "") ;;
  *) printf 'unknown argument: %s\n\n' "$1" >&2; usage >&2; exit 1 ;;
esac

banner "New worktree"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Name the task"

if ! git rev-parse --git-common-dir >/dev/null 2>&1; then
  warn "not inside a git repository — cd into a checkout and re-run"
  exit 1
fi

MAIN=$(cd "$(git rev-parse --git-common-dir)/.." && pwd)
REPO=$(basename "$MAIN")
WT_ROOT="$(dirname "$MAIN")/worktrees/$REPO"

note "canonical checkout: $MAIN"
say "Pick a short slug for the worktree directory (e.g. owl-51-heatmap)."
ask WT_NAME "Worktree name:"
[[ -n "$WT_NAME" ]] || { warn "a name is required"; exit 1; }

WT="$WT_ROOT/$WT_NAME"
[[ -e "$WT" ]] && { warn "$WT already exists"; exit 1; }

say "Branch to work on. Leave blank to reuse the worktree name."
ask WT_BRANCH "Branch:"
WT_BRANCH="${WT_BRANCH:-$WT_NAME}"

say "Base branch to cut from (only used if the branch is new)."
ask WT_BASE "Base [develop]:"
WT_BASE="${WT_BASE:-develop}"

printf '\n'
note "worktree → $WT"
note "branch   → $WT_BRANCH"
if git -C "$MAIN" show-ref --verify --quiet "refs/heads/$WT_BRANCH"; then
  BRANCH_EXISTS=yes
  note "         (branch already exists — it will be checked out, not created)"
else
  BRANCH_EXISTS=no
  note "base     → origin/$WT_BASE"
fi
printf '\n'
confirm "Create it?" || { say "aborted"; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the worktree"

say "Fetching origin so the base branch is current…"
git -C "$MAIN" fetch origin --quiet

mkdir -p "$WT_ROOT"
if [[ "$BRANCH_EXISTS" == yes ]]; then
  git -C "$MAIN" worktree add "$WT" "$WT_BRANCH"
else
  git -C "$MAIN" worktree add -b "$WT_BRANCH" "$WT" "origin/$WT_BASE"
fi
printf '  %s✓%s worktree created at %s\n' "$GREEN" "$RESET" "$WT"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Link the personal layer"

say "These paths are in .git/info/exclude, so git never carries them into a"
say "worktree. They are symlinked — never copied — so edits stay canonical."
printf '\n'

# Relative depth: <parent>/worktrees/<repo>/<name> → <parent>/<repo>
REL="../../../$REPO"
REL_FROM_CLAUDE="../../../../$REPO"

for item in "${PERSONAL_ROOT[@]}"; do
  if [[ -e "$MAIN/$item" ]]; then
    ln -s "$REL/$item" "$WT/$item"
    printf '  %s✓ linked%s %s\n' "$GREEN" "$RESET" "$item"
  else
    note "skipped $item (not present in $REPO)"
  fi
done

mkdir -p "$WT/.claude"
for item in "${PERSONAL_CLAUDE[@]}"; do
  if [[ -e "$MAIN/.claude/$item" ]]; then
    ln -s "$REL_FROM_CLAUDE/.claude/$item" "$WT/.claude/$item"
    printf '  %s✓ linked%s .claude/%s\n' "$GREEN" "$RESET" "$item"
  else
    note "skipped .claude/$item (not present)"
  fi
done
note ".claude/ itself stays a real directory — session state is per-worktree."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Copy the env files"

say "/.env* is gitignored (except .env.test), so the worktree starts with none."
say "These are copied, not linked, so this workspace can run its own port/API."
printf '\n'

shopt -s nullglob
for f in "$MAIN"/.env*; do
  base=$(basename "$f")
  [[ -f "$f" ]] || continue
  if git -C "$MAIN" ls-files --error-unmatch "$base" >/dev/null 2>&1; then
    note "skipped $base (tracked — git already provided it)"
    continue
  fi
  cp "$f" "$WT/$base"
  printf '  %s✓ copied%s %s\n' "$GREEN" "$RESET" "$base"
done
shopt -u nullglob

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Install dependencies"

say "bun install in the worktree — isolated, and it applies patches/."
printf '\n'
if confirm "Run bun install now? (a minute or two)"; then
  (cd "$WT" && bun install)
  printf '  %s✓%s dependencies installed\n' "$GREEN" "$RESET"
else
  SKIPPED+=("bun install (cd $WT && bun install)")
  note "skipped — run it before starting the dev server"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify"

say "The worktree should be clean: if any personal path shows up as untracked,"
say ".git/info/exclude is missing a pattern for it."
printf '\n'

DIRTY=$(git -C "$WT" status --porcelain)
if [[ -z "$DIRTY" ]]; then
  printf '  %s✓%s worktree is clean — the personal layer is fully excluded\n' "$GREEN" "$RESET"
else
  warn "these paths are NOT excluded and would be committed by accident:"
  printf '%s\n' "$DIRTY" | while read -r line; do note "  $line"; done
  SKIPPED+=("add the paths above to $MAIN/.git/info/exclude")
  note "a symlink does not match a trailing-slash pattern — add the slashless"
  note "form too (e.g. both 'docs/' and 'docs')."
fi

printf '\n'
say "Start work with:"
printf '    %scd %s%s\n' "$BOLD" "$WT" "$RESET"
say "When you are done, remove it with:"
printf '    %sgit -C %s worktree remove %s%s\n' "$BOLD" "$MAIN" "$WT" "$RESET"
printf '\n'
pause "Press Enter for the summary"

finish
